{"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","abstract":[{"text":"Authentication is failure - Other error received from server","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"failure"},{"kind":"text","text":"("},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/vigramsdk\/authenticationerror\/failure(_:)"]}],"hierarchy":{"paths":[["doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK","doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/AuthenticationError"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/AuthenticationError\/failure(_:)"},"metadata":{"modules":[{"name":"VigramSDK"}],"title":"AuthenticationError.failure(_:)","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failure","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":")","kind":"text"}],"role":"symbol","roleHeading":"Case","externalID":"s:9VigramSDK19AuthenticationErrorO7failureyACSScACmF","symbolKind":"case"},"references":{"doc://com.vigram.VigramSDK/documentation/VigramSDK/AuthenticationError":{"identifier":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/AuthenticationError","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AuthenticationError"}],"abstract":[{"text":"AuthenticationError contains custom failure events when connecting to Authentication process.","type":"text"}],"title":"AuthenticationError","kind":"symbol","role":"symbol","type":"topic","navigatorTitle":[{"text":"AuthenticationError","kind":"identifier"}],"url":"\/documentation\/vigramsdk\/authenticationerror"},"doc://com.vigram.VigramSDK/documentation/VigramSDK":{"title":"VigramSDK","abstract":[],"url":"\/documentation\/vigramsdk","type":"topic","identifier":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK","role":"collection","images":[{"identifier":"logo.png","type":"icon"}],"kind":"symbol"},"logo.png":{"alt":"Vigram logo.","identifier":"logo.png","variants":[{"url":"\/images\/logo.png","traits":["1x","light"]}],"type":"image"},"doc://com.vigram.VigramSDK/documentation/VigramSDK/AuthenticationError/failure(_:)":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"failure","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"title":"AuthenticationError.failure(_:)","url":"\/documentation\/vigramsdk\/authenticationerror\/failure(_:)","type":"topic","role":"symbol","identifier":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/AuthenticationError\/failure(_:)","abstract":[{"type":"text","text":"Authentication is failure - Other error received from server"}],"kind":"symbol"}}}