{"metadata":{"role":"symbol","externalID":"s:9VigramSDK19AuthenticationErrorO7failureyACSScACmF","title":"AuthenticationError.failure(_:)","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failure"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"symbolKind":"case","modules":[{"name":"VigramSDK"}]},"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/AuthenticationError\/failure(_:)"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"failure","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":")","kind":"text"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/vigramsdk\/authenticationerror\/failure(_:)"]}],"sections":[],"abstract":[{"type":"text","text":"Authentication is failure - Other error received from server"}],"hierarchy":{"paths":[["doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK","doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/AuthenticationError"]]},"references":{"doc://com.vigram.VigramSDK/documentation/VigramSDK/AuthenticationError/failure(_:)":{"url":"\/documentation\/vigramsdk\/authenticationerror\/failure(_:)","role":"symbol","identifier":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/AuthenticationError\/failure(_:)","title":"AuthenticationError.failure(_:)","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"failure"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Authentication is failure - Other error received from server"}],"type":"topic"},"logo.png":{"alt":"Vigram logo.","variants":[{"traits":["1x","light"],"url":"\/images\/logo.png"}],"identifier":"logo.png","type":"image"},"doc://com.vigram.VigramSDK/documentation/VigramSDK":{"identifier":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK","type":"topic","abstract":[],"url":"\/documentation\/vigramsdk","images":[{"type":"icon","identifier":"logo.png"}],"role":"collection","kind":"symbol","title":"VigramSDK"},"doc://com.vigram.VigramSDK/documentation/VigramSDK/AuthenticationError":{"kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AuthenticationError"}],"navigatorTitle":[{"text":"AuthenticationError","kind":"identifier"}],"title":"AuthenticationError","abstract":[{"type":"text","text":"AuthenticationError contains custom failure events when connecting to Authentication process."}],"role":"symbol","identifier":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/AuthenticationError","type":"topic","url":"\/documentation\/vigramsdk\/authenticationerror"}}}