{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"failure"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"languages":["swift"]}]}],"metadata":{"modules":[{"name":"VigramSDK"}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failure"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"roleHeading":"Case","title":"AuthenticationError.failure(_:)","externalID":"s:9VigramSDK19AuthenticationErrorO7failureyACSScACmF","symbolKind":"case"},"identifier":{"url":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/AuthenticationError\/failure(_:)","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","abstract":[{"text":"Authentication is failure - Other error received from server","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK","doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/AuthenticationError"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/vigramsdk\/authenticationerror\/failure(_:)"]}],"references":{"doc://com.vigram.VigramSDK/documentation/VigramSDK":{"type":"topic","role":"collection","title":"VigramSDK","kind":"symbol","url":"\/documentation\/vigramsdk","images":[{"type":"icon","identifier":"logo.png"}],"identifier":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK","abstract":[]},"doc://com.vigram.VigramSDK/documentation/VigramSDK/AuthenticationError/failure(_:)":{"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"failure","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"role":"symbol","abstract":[{"type":"text","text":"Authentication is failure - Other error received from server"}],"kind":"symbol","title":"AuthenticationError.failure(_:)","url":"\/documentation\/vigramsdk\/authenticationerror\/failure(_:)","identifier":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/AuthenticationError\/failure(_:)"},"doc://com.vigram.VigramSDK/documentation/VigramSDK/AuthenticationError":{"role":"symbol","navigatorTitle":[{"text":"AuthenticationError","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AuthenticationError"}],"identifier":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/AuthenticationError","title":"AuthenticationError","type":"topic","abstract":[{"text":"AuthenticationError contains custom failure events when connecting to Authentication process.","type":"text"}],"url":"\/documentation\/vigramsdk\/authenticationerror"},"logo.png":{"identifier":"logo.png","variants":[{"traits":["1x","light"],"url":"\/images\/logo.png"}],"alt":"Vigram logo.","type":"image"}}}