{"abstract":[{"text":"Authentication is failure - Other error received from server","type":"text"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"failure"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}]}],"kind":"declarations"}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/AuthenticationError\/failure(_:)"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK","doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/AuthenticationError"]]},"metadata":{"symbolKind":"case","externalID":"s:9VigramSDK19AuthenticationErrorO7failureyACSScACmF","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"failure","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"title":"AuthenticationError.failure(_:)","role":"symbol","roleHeading":"Case","modules":[{"name":"VigramSDK"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/vigramsdk\/authenticationerror\/failure(_:)"]}],"references":{"doc://com.vigram.VigramSDK/documentation/VigramSDK":{"abstract":[],"title":"VigramSDK","identifier":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK","type":"topic","url":"\/documentation\/vigramsdk","role":"collection","kind":"symbol","images":[{"type":"icon","identifier":"logo.png"}]},"logo.png":{"alt":"Vigram logo.","identifier":"logo.png","type":"image","variants":[{"traits":["1x","light"],"url":"\/images\/logo.png"}]},"doc://com.vigram.VigramSDK/documentation/VigramSDK/AuthenticationError/failure(_:)":{"identifier":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/AuthenticationError\/failure(_:)","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"failure","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"title":"AuthenticationError.failure(_:)","abstract":[{"type":"text","text":"Authentication is failure - Other error received from server"}],"role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/vigramsdk\/authenticationerror\/failure(_:)"},"doc://com.vigram.VigramSDK/documentation/VigramSDK/AuthenticationError":{"type":"topic","title":"AuthenticationError","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"AuthenticationError","kind":"identifier"}],"identifier":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/AuthenticationError","abstract":[{"type":"text","text":"AuthenticationError contains custom failure events when connecting to Authentication process."}],"url":"\/documentation\/vigramsdk\/authenticationerror","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"AuthenticationError","kind":"identifier"}]}}}